# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-14 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='asa',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='Ic \u043f\u0440\u0438 4.2\u041a, uA'),
        ),
    ]
