# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20181218_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='asa',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='\u041c\u0438\u043a\u0440\u043e\u0441\u043a\u043e\u043f'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=500, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043f\u0430\u0440\u0442\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043f\u0430\u0440\u0442\u0438\u0438'),
        ),
    ]
